# (input, expected html) from the CommonMark 0.31 emphasis section (inline content only)
EXAMPLES = [
 ("*foo bar*", "<em>foo bar</em>"),
 ("a * foo bar*", "a * foo bar*"),
 ('a*"foo"*', "a*&quot;foo&quot;*"),
 ("* a *", "* a *"),
 ("foo*bar*", "foo<em>bar</em>"),
 ("5*6*78", "5<em>6</em>78"),
 ("_foo bar_", "<em>foo bar</em>"),
 ("_ foo bar_", "_ foo bar_"),
 ('a_"foo"_', "a_&quot;foo&quot;_"),
 ("foo_bar_", "foo_bar_"),
 ("5_6_78", "5_6_78"),
 ("пристаням_стремятся_", "пристаням_стремятся_"),
 ('aa_"bb"_cc', "aa_&quot;bb&quot;_cc"),
 ("foo-_(bar)_", "foo-<em>(bar)</em>"),
 ("_foo*", "_foo*"),
 ("*foo bar *", "*foo bar *"),
 ("*foo bar\n*", "*foo bar\n*"),
 ("*(*foo)", "*(*foo)"),
 ("*(*foo*)*", "<em>(<em>foo</em>)</em>"),
 ("*foo*bar", "<em>foo</em>bar"),
 ("_foo bar _", "_foo bar _"),
 ("_(_foo)", "_(_foo)"),
 ("_(_foo_)_", "<em>(<em>foo</em>)</em>"),
 ("_foo_bar", "_foo_bar"),
 ("_пристаням_стремятся", "_пристаням_стремятся"),
 ("_foo_bar_baz_", "<em>foo_bar_baz</em>"),
 ("_(bar)_.", "<em>(bar)</em>."),
 ("**foo bar**", "<strong>foo bar</strong>"),
 ("** foo bar**", "** foo bar**"),
 ('a**"foo"**', "a**&quot;foo&quot;**"),
 ("foo**bar**", "foo<strong>bar</strong>"),
 ("__foo bar__", "<strong>foo bar</strong>"),
 ("__ foo bar__", "__ foo bar__"),
 ("__\nfoo bar__", "__\nfoo bar__"),
 ('a__"foo"__', "a__&quot;foo&quot;__"),
 ("foo__bar__", "foo__bar__"),
 ("5__6__78", "5__6__78"),
 ("пристаням__стремятся__", "пристаням__стремятся__"),
 ("__foo, __bar__, baz__", "<strong>foo, <strong>bar</strong>, baz</strong>"),
 ("foo-__(bar)__", "foo-<strong>(bar)</strong>"),
 ("**foo bar **", "**foo bar **"),
 ("**(**foo)", "**(**foo)"),
 ("*(**foo**)*", "<em>(<strong>foo</strong>)</em>"),
 ("**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**",
  "<strong>Gomphocarpus (<em>Gomphocarpus physocarpus</em>, syn.\n<em>Asclepias physocarpa</em>)</strong>"),
 ('**foo "*bar*" foo**', "<strong>foo &quot;<em>bar</em>&quot; foo</strong>"),
 ("**foo**bar", "<strong>foo</strong>bar"),
 ("__foo bar __", "__foo bar __"),
 ("__(__foo)", "__(__foo)"),
 ("_(__foo__)_", "<em>(<strong>foo</strong>)</em>"),
 ("__foo__bar", "__foo__bar"),
 ("__пристаням__стремятся", "__пристаням__стремятся"),
 ("__foo__bar__baz__", "<strong>foo__bar__baz</strong>"),
 ("__(bar)__.", "<strong>(bar)</strong>."),
 ("*foo\nbar*", "<em>foo\nbar</em>"),
 ("_foo __bar__ baz_", "<em>foo <strong>bar</strong> baz</em>"),
 ("_foo _bar_ baz_", "<em>foo <em>bar</em> baz</em>"),
 ("__foo_ bar_", "<em><em>foo</em> bar</em>"),
 ("*foo *bar**", "<em>foo <em>bar</em></em>"),
 ("*foo **bar** baz*", "<em>foo <strong>bar</strong> baz</em>"),
 ("*foo**bar**baz*", "<em>foo<strong>bar</strong>baz</em>"),
 ("*foo**bar*", "<em>foo**bar</em>"),
 ("***foo** bar*", "<em><strong>foo</strong> bar</em>"),
 ("*foo **bar***", "<em>foo <strong>bar</strong></em>"),
 ("*foo**bar***", "<em>foo<strong>bar</strong></em>"),
 ("foo***bar***baz", "foo<em><strong>bar</strong></em>baz"),
 ("foo******bar*********baz", "foo<strong><strong><strong>bar</strong></strong></strong>***baz"),
 ("*foo **bar *baz* bim** bop*", "<em>foo <strong>bar <em>baz</em> bim</strong> bop</em>"),
 ("** is not an empty emphasis", "** is not an empty emphasis"),
 ("**** is not an empty strong emphasis", "**** is not an empty strong emphasis"),
 ("__foo _bar_ baz__", "<strong>foo <em>bar</em> baz</strong>"),
 ("__foo __bar__ baz__", "<strong>foo <strong>bar</strong> baz</strong>"),
 ("____foo__ bar__", "<strong><strong>foo</strong> bar</strong>"),
 ("**foo **bar****", "<strong>foo <strong>bar</strong></strong>"),
 ("**foo *bar* baz**", "<strong>foo <em>bar</em> baz</strong>"),
 ("**foo*bar*baz**", "<strong>foo<em>bar</em>baz</strong>"),
 ("***foo* bar**", "<strong><em>foo</em> bar</strong>"),
 ("**foo *bar***", "<strong>foo <em>bar</em></strong>"),
 ("**foo *bar **baz**\nbim* bop**", "<strong>foo <em>bar <strong>baz</strong>\nbim</em> bop</strong>"),
 ("__ is not an empty emphasis", "__ is not an empty emphasis"),
 ("____ is not an empty strong emphasis", "____ is not an empty strong emphasis"),
 ("foo ***", "foo ***"),
 ("foo *\\**", "foo <em>*</em>"),
 ("foo *_*", "foo <em>_</em>"),
 ("foo *****", "foo *****"),
 ("foo **\\***", "foo <strong>*</strong>"),
 ("foo **_**", "foo <strong>_</strong>"),
 ("**foo*", "*<em>foo</em>"),
 ("*foo**", "<em>foo</em>*"),
 ("***foo**", "*<strong>foo</strong>"),
 ("****foo*", "***<em>foo</em>"),
 ("**foo***", "<strong>foo</strong>*"),
 ("*foo****", "<em>foo</em>***"),
 ("foo ___", "foo ___"),
 ("foo _\\__", "foo <em>_</em>"),
 ("foo _*_", "foo <em>*</em>"),
 ("foo _____", "foo _____"),
 ("foo __\\___", "foo <strong>_</strong>"),
 ("foo __*__", "foo <strong>*</strong>"),
 ("__foo_", "_<em>foo</em>"),
 ("_foo__", "<em>foo</em>_"),
 ("___foo__", "_<strong>foo</strong>"),
 ("____foo_", "___<em>foo</em>"),
 ("__foo___", "<strong>foo</strong>_"),
 ("_foo____", "<em>foo</em>___"),
 ("**foo**", "<strong>foo</strong>"),
 ("*_foo_*", "<em><em>foo</em></em>"),
 ("__foo__", "<strong>foo</strong>"),
 ("_*foo*_", "<em><em>foo</em></em>"),
 ("****foo****", "<strong><strong>foo</strong></strong>"),
 ("____foo____", "<strong><strong>foo</strong></strong>"),
 ("******foo******", "<strong><strong><strong>foo</strong></strong></strong>"),
 ("***foo***", "<em><strong>foo</strong></em>"),
 ("_____foo_____", "<em><strong><strong>foo</strong></strong></em>"),
 ("*foo _bar* baz_", "<em>foo _bar</em> baz_"),
 ("*foo __bar *baz bim__ bam*", "<em>foo <strong>bar *baz bim</strong> bam</em>"),
 ("**foo **bar baz**", "**foo <strong>bar baz</strong>"),
 ("*foo *bar baz*", "*foo <em>bar baz</em>"),
 ("*a `*`*", "<em>a <code>*</code></em>"),
 ("_a `_`_", "<em>a <code>_</code></em>"),
 ("*foo\\*bar*", "<em>foo*bar</em>"),
 ("\\*not emphasis*", "*not emphasis*"),
 ("**foo\\**", "*<em>foo*</em>"),
]
